
DROP TABLE IF EXISTS  STUDENTS ;
CREATE TABLE  STUDENTS  (
   STUDENT_ID  int(11) NOT NULL DEFAULT '0',
   FIRST_NAME  varchar(20) DEFAULT NULL,
   LAST_NAME  varchar(20) DEFAULT NULL,
   DATE_OF_BIRTH  varchar(20) DEFAULT NULL,
   GRADE  varchar(20) DEFAULT NULL,
   GENDER  varchar(20) DEFAULT NULL,
  PRIMARY KEY ( STUDENT_ID )
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO  STUDENTS  VALUES (45,'Mayooran','Somasundaram','12/10/1964', '5', 'Male');




